[package]
name = "tui_example_apps"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.28.1"
ratatui = { version = "0.29.0", features = ["all-widgets"] }
serde_json = "1.0.133"
